import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../../project/models/project.dart';
import '../../project/models/file_change.dart';
import '../../../shared/widgets/kindle_card.dart';
import '../../../shared/widgets/section_title.dart';
import '../../../shared/widgets/empty_state.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/constants/app_constants.dart';
import '../../../core/utils/responsive_layout.dart';

class GeneratedChangesScreen extends StatelessWidget {
  final Project project;

  const GeneratedChangesScreen({super.key, required this.project});

  @override
  Widget build(BuildContext context) {
    final displayChanges = project.fileChanges;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Generated Changes'),
      ),
      body: displayChanges.isEmpty
          ? const KindleEmptyState(
              title: 'No Generated Changes',
              message: 'File modifications generated by AI agents will appear here.',
              icon: Icons.history,
            )
          : Center(
              child: ConstrainedBox(
                constraints: const BoxConstraints(maxWidth: kMaxContentWidth),
                child: ListView.builder(
                  padding: const EdgeInsets.all(AppConstants.spacingMd),
                  itemCount: displayChanges.length + 1,
                  itemBuilder: (context, index) {
                    if (index == 0) {
                      return const SectionTitle(
                        title: 'File Change History',
                        subtitle: 'Audit trail of all autonomous modifications.',
                      );
                    }
                    final change = displayChanges[index - 1];
                    return _FileChangeCard(change: change);
                  },
                ),
              ),
            ),
    );
  }
}

class _FileChangeCard extends StatelessWidget {
  final FileChange change;

  const _FileChangeCard({required this.change});

  @override
  Widget build(BuildContext context) {
    final timeStr = DateFormat('MMM d, HH:mm').format(change.timestamp);

    return Padding(
      padding: const EdgeInsets.only(bottom: AppConstants.spacingMd),
      child: KindleCard(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                _ChangeTypeIcon(type: change.type),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        change.filePath,
                        style: const TextStyle(
                          fontFamily: 'monospace',
                          fontWeight: FontWeight.bold,
                          fontSize: 13,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        'By ${change.agentName} • $timeStr',
                        style: Theme.of(context).textTheme.labelSmall?.copyWith(color: AppColors.textSecondary),
                      ),
                    ],
                  ),
                ),
                _ChangeTypeBadge(type: change.type),
              ],
            ),
            const Divider(height: AppConstants.spacingLg),
            Row(
              children: [
                const Icon(Icons.assignment_outlined, size: 14, color: AppColors.textSecondary),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    'Task: ${change.taskTitle}',
                    style: Theme.of(context).textTheme.bodySmall,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _ChangeTypeIcon extends StatelessWidget {
  final FileChangeType type;
  const _ChangeTypeIcon({required this.type});

  @override
  Widget build(BuildContext context) {
    IconData icon;
    Color color;
    switch (type) {
      case FileChangeType.created:
        icon = Icons.add_circle_outline;
        color = Colors.green;
        break;
      case FileChangeType.modified:
        icon = Icons.edit_note;
        color = Colors.blue;
        break;
      case FileChangeType.deleted:
        icon = Icons.remove_circle_outline;
        color = Colors.red;
        break;
    }
    return CircleAvatar(
      radius: 16,
      backgroundColor: color.withValues(alpha: 0.1),
      child: Icon(icon, color: color, size: 18),
    );
  }
}

class _ChangeTypeBadge extends StatelessWidget {
  final FileChangeType type;
  const _ChangeTypeBadge({required this.type});

  @override
  Widget build(BuildContext context) {
    Color color;
    switch (type) {
      case FileChangeType.created:
        color = Colors.green;
        break;
      case FileChangeType.modified:
        color = Colors.blue;
        break;
      case FileChangeType.deleted:
        color = Colors.red;
        break;
    }

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(4),
      ),
      child: Text(
        type.name.toUpperCase(),
        style: TextStyle(color: color, fontSize: 8, fontWeight: FontWeight.bold),
      ),
    );
  }
}
