import 'package:flutter/material.dart';
import '../models/file_node.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/utils/responsive_layout.dart';

class GeneratedCodeScreen extends StatefulWidget {
  const GeneratedCodeScreen({super.key});

  @override
  State<GeneratedCodeScreen> createState() => _GeneratedCodeScreenState();
}

class _GeneratedCodeScreenState extends State<GeneratedCodeScreen> {
  FileNode? _selectedFile;
  late List<FileNode> _fileSystem;

  @override
  void initState() {
    super.initState();
    _fileSystem = _generateMockFileSystem();
  }

  List<FileNode> _generateMockFileSystem() {
    return [
      FileNode(
        name: 'lib',
        isFolder: true,
        isExpanded: true,
        children: [
          FileNode(
            name: 'core',
            isFolder: true,
            children: [
              FileNode(name: 'app_theme.dart', content: 'class AppTheme { ... }'),
              FileNode(name: 'app_colors.dart', content: 'class AppColors { ... }'),
            ],
          ),
          FileNode(
            name: 'features',
            isFolder: true,
            isExpanded: true,
            children: [
              FileNode(
                name: 'auth',
                isFolder: true,
                children: [
                  FileNode(name: 'login_screen.dart', content: 'class LoginScreen extends StatelessWidget { ... }'),
                  FileNode(name: 'auth_viewmodel.dart', content: 'class AuthViewModel extends ChangeNotifier { ... }'),
                ],
              ),
              FileNode(
                name: 'chat',
                isFolder: true,
                children: [
                  FileNode(name: 'chat_screen.dart', content: 'class ChatScreen extends StatefulWidget { ... }'),
                ],
              ),
            ],
          ),
          FileNode(name: 'main.dart', content: 'void main() { runApp(const KindleApp()); }'),
        ],
      ),
      FileNode(name: 'pubspec.yaml', content: 'name: sparked_app\ndependencies:\n  flutter: sdk: flutter'),
      FileNode(name: 'README.md', content: '# Sparked Project\nGenerated by Kindle AI.'),
    ];
  }

  @override
  Widget build(BuildContext context) {
    final bool isDesktop = ResponsiveLayout.isDesktop(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Generated Source'),
        actions: [
          IconButton(icon: const Icon(Icons.download_outlined), onPressed: () {}),
          IconButton(icon: const Icon(Icons.copy_all), onPressed: () {}),
        ],
      ),
      body: Row(
        children: [
          // File Explorer
          SizedBox(
            width: isDesktop ? 300 : 200,
            child: Container(
              decoration: BoxDecoration(
                border: Border(right: BorderSide(color: Colors.grey.shade200)),
              ),
              child: ListView(
                padding: const EdgeInsets.symmetric(vertical: 8),
                children: _fileSystem.map((node) => _FileTreeItem(
                  node: node,
                  level: 0,
                  onSelected: (selected) {
                    setState(() {
                      _selectedFile = selected;
                    });
                  },
                )).toList(),
              ),
            ),
          ),
          // Code Viewer Placeholder
          Expanded(
            child: _selectedFile == null
                ? _buildEmptyState()
                : _buildCodeViewer(),
          ),
        ],
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.code_off, size: 64, color: Colors.grey.shade300),
          const SizedBox(height: 16),
          const Text('Select a file to view code', style: TextStyle(color: Colors.grey)),
        ],
      ),
    );
  }

  Widget _buildCodeViewer() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
          color: Colors.grey.shade50,
          child: Row(
            children: [
              const Icon(Icons.description_outlined, size: 16, color: AppColors.primary),
              const SizedBox(width: 8),
              Text(
                _selectedFile!.name,
                style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 13),
              ),
            ],
          ),
        ),
        Expanded(
          child: Container(
            padding: const EdgeInsets.all(16),
            color: const Color(0xFFF8F8F8),
            child: SingleChildScrollView(
              child: Text(
                _selectedFile!.content ?? '',
                style: const TextStyle(
                  fontFamily: 'monospace',
                  fontSize: 14,
                  height: 1.5,
                  color: Color(0xFF333333),
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }
}

class _FileTreeItem extends StatefulWidget {
  final FileNode node;
  final int level;
  final Function(FileNode) onSelected;

  const _FileTreeItem({
    required this.node,
    required this.level,
    required this.onSelected,
  });

  @override
  State<_FileTreeItem> createState() => _FileTreeItemState();
}

class _FileTreeItemState extends State<_FileTreeItem> {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        InkWell(
          onTap: () {
            if (widget.node.isFolder) {
              setState(() {
                widget.node.isExpanded = !widget.node.isExpanded;
              });
            } else {
              widget.onSelected(widget.node);
            }
          },
          child: Padding(
            padding: EdgeInsets.only(
              left: 16.0 + (widget.level * 16.0),
              top: 4,
              bottom: 4,
              right: 8,
            ),
            child: Row(
              children: [
                Icon(
                  widget.node.isFolder
                      ? (widget.node.isExpanded ? Icons.keyboard_arrow_down : Icons.keyboard_arrow_right)
                      : Icons.description_outlined,
                  size: 16,
                  color: Colors.grey.shade600,
                ),
                const SizedBox(width: 8),
                Icon(
                  widget.node.isFolder ? Icons.folder_open : Icons.code,
                  size: 16,
                  color: widget.node.isFolder ? Colors.amber.shade700 : Colors.blue.shade700,
                ),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    widget.node.name,
                    style: const TextStyle(fontSize: 13),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
          ),
        ),
        if (widget.node.isFolder && widget.node.isExpanded && widget.node.children != null)
          ...widget.node.children!.map((child) => _FileTreeItem(
                node: child,
                level: widget.level + 1,
                onSelected: widget.onSelected,
              )),
      ],
    );
  }
}
